/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.DonorBank;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem.EcoSystem;
import Business.Enterprise.DonorBank.Donor;
import Business.Enterprise.DonorBank.DonorBank;
import Business.Firebase.FirebaseHelper;
import UserInterface.DonorBank.LoginPages.DonorBankAdminLogin;
import UserInterface.DonorBank.LoginPages.DonorLogin;
import UserInterface.MainFrameForm;
import javax.swing.JOptionPane;

/**
 *
 * @author Mayur
 */
public class MainDonorBankPage extends javax.swing.JPanel {

    /**
     * Creates new form MainDonorBankPage
     */
    MainFrameForm mainScreen;
    private DB4OUtil dB4OUtil;
    private EcoSystem ecoSystem;

    public MainDonorBankPage(MainFrameForm mainScreen, DB4OUtil dB4OUtil, EcoSystem ecoSystem) {
        initComponents();
        this.mainScreen = mainScreen;
        this.dB4OUtil = dB4OUtil;
        this.ecoSystem = ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_role = new javax.swing.JLabel();
        cmb_Role = new javax.swing.JComboBox<>();
        lbl_username = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lbl_pswd = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSignin = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Donor Bank");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 50, -1, -1));

        lbl_role.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_role.setText("Role:");
        add(lbl_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 189, -1, -1));

        cmb_Role.setEditable(true);
        cmb_Role.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_Role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Donor","Donor Admin"}));
        cmb_Role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_RoleActionPerformed(evt);
            }
        });
        add(cmb_Role, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 215, 197, -1));

        lbl_username.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_username.setText("Username:");
        add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 252, -1, -1));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 278, 197, -1));

        lbl_pswd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_pswd.setText("Password:");
        add(lbl_pswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 322, -1, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 348, 197, -1));

        btn_login.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 411, 86, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Donor2.v4.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 750));

        btnSignin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSignin.setText("Sign Up");
        btnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigninActionPerformed(evt);
            }
        });
        add(btnSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 411, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_RoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_RoleActionPerformed
        // TODO add your handling code here:
        System.out.println(cmb_Role.getSelectedItem().toString());
        if (cmb_Role.getSelectedItem().toString() == "Admin") {
            btnSignin.setEnabled(false);
        } else {
            btnSignin.setEnabled(true);
        }
    }//GEN-LAST:event_cmb_RoleActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        
        if (cmb_Role.getSelectedItem().toString() == "Donor Admin") {
            DonorBank donbank = (DonorBank) ecoSystem.loginCheck(txtUsername.getText(), txtPassword.getText());
            if(donbank == null){
                JOptionPane.showMessageDialog(this, "Incorrect credential");
            }else{
                DonorBankAdminLogin ap = new DonorBankAdminLogin(mainScreen, dB4OUtil, ecoSystem, donbank);
                mainScreen.setContentPane(ap);
                mainScreen.invalidate();
                mainScreen.validate();
                return;
            }
        }
        
        if (cmb_Role.getSelectedItem().toString() == "Donor") {
            Donor don = (Donor) ecoSystem.loginCheck(txtUsername.getText(), txtPassword.getText());
            if(don == null){
                JOptionPane.showMessageDialog(this, "Incorrect credential");
            }else{
                DonorLogin ap = new DonorLogin(mainScreen, dB4OUtil, ecoSystem, don);
                mainScreen.setContentPane(ap);
                mainScreen.invalidate();
                mainScreen.validate();
                return;
            }
        }

        //        if (cmb_Role.getSelectedItem().toString() == "Doctor") {
        //            Customer c = system.loginCustomer(txtUsername.getText(), txtPassword.getText());
        //            if (c == null) {
        //                JOptionPane.showMessageDialog(this, "Incorrect credential");
        //            } else {
        //                CustomerMainPage custmp = new CustomerMainPage(system, dB4OUtil, c);
        //                this.setContentPane(custmp);
        //                this.invalidate();
        //                this.validate();
        //                return;
        //            }
        //
        //        }
        //        if (cmb_Role.getSelectedItem().toString() == "Nurse") {
        //            Restaurant r = system.loginResaturant(txtUsername.getText(), txtPassword.getText());
        //
        //            if (r == null) {
        //                JOptionPane.showMessageDialog(this, "Incorrect credential");
        //            } else {
        //                RestaurantMainPage restmp = new RestaurantMainPage(system, dB4OUtil, r);
        //                this.setContentPane(restmp);
        //                this.invalidate();
        //                this.validate();
        //                return;
        //            }
        //
        //        }
        //
        //        if (cmb_Role.getSelectedItem().toString() == "Patient") {
        //            DeliveryMan r = system.loginDeliveryMan(txtUsername.getText(), txtPassword.getText());
        //
        //            if (r == null) {
        //                JOptionPane.showMessageDialog(this, "Incorrect credential");
        //            } else {
        //                DeliverManMainPage delimp = new DeliverManMainPage(system, dB4OUtil, r);
        //                this.setContentPane(delimp);
        //                this.invalidate();
        //                this.validate();
        //                return;
        //            }
        //
        //        }
        //
        //        if (cmb_Role.getSelectedItem().toString() == "Hospital Admin") {
        //            if (txtUsername.getText().matches("a") && txtPassword.getText().matches("a")) {
        //                AdminPage adminpg = new AdminPage(system, dB4OUtil);
        //                this.setContentPane(adminpg);
        //                this.invalidate();
        //                this.validate();
        //                return;
        //            } else {
        //                JOptionPane.showMessageDialog(this, "Incorrect credential");
        //            }
        //        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
        // TODO add your handling code here:

       
        if (cmb_Role.getSelectedItem().toString() == "Donor") {

            SignUpDonor signdon = new SignUpDonor(mainScreen, dB4OUtil, ecoSystem);
//
//            //suc.setVisible(true);
            mainScreen.setContentPane(signdon);
////            //             this.add(s);
////
            mainScreen.invalidate();
            mainScreen.validate();

        }

        if (cmb_Role.getSelectedItem().toString() == "Donor Admin") {
           // System.out.println("Hospital");
            SignUpDonorAdmin s = new SignUpDonorAdmin(mainScreen, dB4OUtil, ecoSystem);

            //suc.setVisible(true);
            mainScreen.setContentPane(s);
            //             this.add(s);

            mainScreen.invalidate();
            mainScreen.validate();

        }
    }//GEN-LAST:event_btnSigninActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignin;
    private javax.swing.JButton btn_login;
    private javax.swing.JComboBox<String> cmb_Role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_pswd;
    private javax.swing.JLabel lbl_role;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
